networks:
  tv:
    driver: bridge

services:
  mirakurun:
    container_name: mirakurun-4.0.0
    build:
      context: ./mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    networks:
      - tv
    ports:
      - "40772:40772"
      # - "9229:9229"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mirakurun/conf:/app-config
      - ./mirakurun/data:/app-data
    environment:
      TZ: Asia/Tokyo
    devices:
      - /dev/bus:/dev/bus
      - /dev/px4video0:/dev/px4video0
      - /dev/px4video1:/dev/px4video1
      - /dev/px4video2:/dev/px4video2
      - /dev/px4video3:/dev/px4video3
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: 1
        max-size: 10m

  konomitv:
    container_name: KonomiTV
    build:
      context: https://github.com/tsukumijima/KonomiTV.git
      dockerfile: Dockerfile
    init: true
    restart: unless-stopped
    networks:
      - tv
    depends_on:
      - mirakurun
    volumes:
      - type: bind
        source: ./KonomiTV/config.yaml
        target: /code/config.yaml
      - type: bind
        source: ./KonomiTV/server/data/
        target: /code/server/data/
      - type: bind
        source: ./KonomiTV/server/logs/
        target: /code/server/logs/
      - type: bind
        source: ./KonomiTV/data/record
        target: /host-rootfs/KonomiTV/data/record
      - type: bind
        source: ./KonomiTV/data/capture
        target: /host-rootfs/KonomiTV/data/capture
    devices:
      - /dev/dri/:/dev/dri/
    ports:
      - 7000:7000

  mysql:
    image: mariadb:11.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: epgstation
      MYSQL_PASSWORD: epgstation
      MYSQL_ROOT_PASSWORD: epgstation
      MYSQL_DATABASE: epgstation
      TZ: Asia/Tokyo
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --performance-schema=false
      - --expire_logs_days=1
    restart: unless-stopped
    networks:
      - tv
    logging:
      options:
        max-size: 10m
        max-file: 3

  epgstation:
    build:
      context: ./epgstation
      dockerfile: debian.Dockerfile
    volumes:
      - ./epgstation/config:/app/config
      - ./epgstation/data:/app/data
      - ./epgstation/thumbnail:/app/thumbnail
      - ./epgstation/logs:/app/logs
      - ./recorded:/app/recorded
    environment:
      TZ: Asia/Tokyo
    networks:
      - tv
    depends_on:
      - mirakurun
      - mysql
    ports:
      - 9999:8888
    restart: unless-stopped
