services:
  mirakc:
    container_name: mirakc
    build:
      context: https://github.com/mirakc/mirakc.git
      dockerfile: docker/Dockerfile.alpine
    init: true
    restart: unless-stopped
    # network_mode: host
    volumes:
      - ./mirakc/epg:/var/lib/mirakc/epg
      - ./mirakc/config.yaml:/etc/mirakc/config.yml:ro
    environment:
      TZ: Asia/Tokyo
      RUST_LOG: info
    devices:
      - /dev/px4video0
      - /dev/px4video1
      - /dev/px4video2
      - /dev/px4video3
    ports:
      - 40772:40772

  bcas:
    build: ./bcas
    container_name: bcas
    init: true
    restart: unless-stopped
    # network_mode: host
    environment:
      TZ: Asia/Tokyo
    devices:
      # ICカードリーダーを追加
      - /dev/bus/usb
    ports:
      - 40774:40774/tcp

  b25:
    build: ./b25
    container_name: b25
    depends_on:
      - bcas
    init: true
    restart: unless-stopped
    # network_mode: host
    environment:
      BCAS_SERVER: bcas:40774
      TZ: Asia/Tokyo
    ports:
      - 40773:40773/tcp

  edcb_chscan:
    container_name: EDCB_ChScan
    build:
      context: ./EDCB
    init: true
    # network_mode: host
    depends_on:
      - mirakc
      - b25
    command: /usr/local/bin/EpgDataCap_Bon -d BonDriver_LinuxMirakc.so -chscan
    volumes:
      - type: bind
        source: "./EDCB/Common.ini"
        target: "/var/local/edcb/Common.ini"
      - type: bind
        source: "./EDCB/EpgDataCap_Bon.ini"
        target: "/var/local/edcb/EpgDataCap_Bon.ini"
      - type: bind
        source: "./EDCB/EpgTimerSrv.ini"
        target: "/var/local/edcb/EpgTimerSrv.ini"
      - type: bind
        source: "./EDCB/Setting"
        target: "/var/local/edcb/Setting"

  edcb:
    container_name: EDCB
    build:
      context: ./EDCB
    depends_on:
      mirakc:
        condition: service_started
      b25:
        condition: service_started
      edcb_chscan:
        condition: service_completed_successfully
    init: true
    restart: unless-stopped
    # network_mode: host
    volumes:
      - type: bind
        source: "./EDCB/Common.ini"
        target: "/var/local/edcb/Common.ini"
      - type: bind
        source: "./EDCB/EpgDataCap_Bon.ini"
        target: "/var/local/edcb/EpgDataCap_Bon.ini"
      - type: bind
        source: "./EDCB/EpgTimerSrv.ini"
        target: "/var/local/edcb/EpgTimerSrv.ini"
      - type: bind
        source: "./EDCB/Setting"
        target: "/var/local/edcb/Setting"
      - type: bind
        source: "./EDCB/record"
        target: "/record"
    ports:
      - 4510:4510/tcp

  konomitv:
    container_name: KonomiTV
    build:
      context: https://github.com/tsukumijima/KonomiTV.git
      dockerfile: Dockerfile
    init: true
    restart: unless-stopped
    # network_mode: host
    depends_on:
      - mirakc
      - b25
      - edcb
    volumes:
      - type: bind
        source: './KonomiTV/config.yaml'
        target: '/code/config.yaml'
      - type: bind
        source: './KonomiTV/server/data/'
        target: '/code/server/data/'
      - type: bind
        source: './KonomiTV/server/logs/'
        target: '/code/server/logs/'
      - type: bind
        source: './KonomiTV/data/record'
        target: '/host-rootfs/KonomiTV/data/record'
      - type: bind
        source: './KonomiTV/data/capture'
        target: '/host-rootfs/KonomiTV/data/capture'
    devices:
      - '/dev/dri/:/dev/dri/'
