epg:
  cache-dir: /var/lib/mirakc/epg

server:
  addrs:
    - http: '0.0.0.0:40772'

tuners:
  - name: GR0
    types: [GR]
    command: recpt1 --device /dev/px4video2 {{{channel}}} - -
  - name: GR1
    types: [GR]
    command: recpt1 --device /dev/px4video3 {{{channel}}} - -
  - name: BSCS0
    types: [BS, CS]
    command: recpt1 --device /dev/px4video0 {{{channel}}} - -
  - name: BSCS1
    types: [BS, CS]
    command: recpt1 --device /dev/px4video1 {{{channel}}} - -

filters:
  # Optionally, you can specify a command to process TS packets before sending
  # them to a client.
  #
  # The following command processes TS packets on a remote server listening on
  # TCP port 40774.
  decode-filter:
    command: >-
      socat -,cool-write tcp-connect:b25:40773

channels:
  - name: 'スカパー！ナビ１'
    type: 'GR'
    channel: '17'
    extra-args: ''
    disabled: false

  - name: 'ＴＯＫＹＯ　ＭＸ１'
    type: 'GR'
    channel: '20'
    extra-args: ''
    disabled: false

  - name: 'フジテレビ'
    type: 'GR'
    channel: '21'
    extra-args: ''
    disabled: false

  - name: 'ＴＢＳ１'
    type: 'GR'
    channel: '22'
    extra-args: ''
    disabled: false

  - name: 'テレ東'
    type: 'GR'
    channel: '23'
    extra-args: ''
    disabled: false

  - name: 'テレビ朝日'
    type: 'GR'
    channel: '24'
    extra-args: ''
    disabled: false

  - name: '日テレ１'
    type: 'GR'
    channel: '25'
    extra-args: ''
    disabled: false

  - name: 'ＮＨＫＥテレ１東京'
    type: 'GR'
    channel: '26'
    extra-args: ''
    disabled: false

  - name: 'ＮＨＫ総合１・東京'
    type: 'GR'
    channel: '27'
    extra-args: ''
    disabled: false
